# Describe a service that consists of our web app pods
apiVersion: v1
kind: Service
metadata:
  name: remind-me-web-svc
  labels:
    app: remind-me-web-svc
spec:
  type: NodePort # type of service
  ports:
    - port: 8080 # any service in the same namespace can talk to this service using this port.
      protocol: TCP
      targetPort: 80 # our web application is running on this port in pod. By default, targetPort = port.
      nodePort: 31120 # external users can access this service on port 31120 using kube-proxy.
  selector:
    app: remindmeweb
---
# Replicaset for frontend
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: remindmeweb-replicaset
  labels:
    app: remindmeweb
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: remindmeweb # I'll deploy to all pods that have this label
  template:
    metadata:
      labels:
        app: remindmeweb
    spec:
      containers:
        - name: frontend2
          image: kubernetessuccinctly/remind-me-web:2.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: env
          ports:
            - containerPort: 80
              protocol: TCP
